config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :profiles, only: [:new, :edit, :create, :update]
  get '/profiles/:id', to: 'profiles#show', as: 'user_profile'
  delete '/profiles/:id', to: 'profiles#destroy', as: 'delete_user_profile'
  delete '/profiles/:id/remove_image', to: 'profiles#remove_image', as: 'remove_profile_image'

  get '/dashboard', to: 'profiles#dashboard', as: 'request_dashboard'
  get '/profiles/:id/dashboard', to: 'profiles#dashboard', as: 'dashboard'

  resources :pets do
    resources :requests, only: [:create] do
      post :accept, on: :member
      post :decline, on: :member
    end
    collection do
      get :pet_listings
    end
  end

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :requests
  belongs_to :user
  validates :name, :address, :age, :postcode, :description, :price, :start_date, :end_date, :category, :country, :city, presence: true
  validates :photo, presence: true, unless: -> { new_record? || seeding? }

  attr_accessor :seeding

  def seeding?
    seeding == true
  end
  has_one_attached :photo
  enum category: {
    "Dog" => 0,
    "Cat" => 1,
    "Rabbit" => 2,
    "Ferret" => 3,
    "Fish" => 4,
    "Bird" => 5,
    "Other" => 6
  }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_one_attached :photo
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :pet
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets
  has_many :requests
  has_many :pet_requests, through: :pets, source: :requests
  has_one  :profile
  has_many :reviews

  # PET OWNER START
  def pet_owner?
    profile.present? && profile.role == 'pet_owner'
  end

  def owner_pets
    pets if pet_owner?
  end
  # PET OWNER END

  # PET SITTER START
  def pet_sitter?
    profile.present? && profile.role == 'pet_sitter'
  end

  def sitter_pets
    pets if pet_sitter?
  end
  # PET SITTER END

  # PET BOTH START
  def both?
    profile.present? && profile.role == 'both'
  end

  def both_pets
    pets if both?
  end
  # PET BOTH END
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :description])
  end

  def after_sign_in_path_for(resource)
    if resource.profile.present?
      root_path
    else
      new_profile_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pets = Pet.last(6)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    puts "Received params: #{params.inspect}"
    @pet = Pet.new
    @pets = Pet.all
    @pets = Pet.where(category: params[:category]) if params[:category].present?
    @pets = @pets.where("START_DATE >= ?", params[:start_date]) if params[:start_date].present?
    @pets = @pets.where("END_DATE <= ?", params[:end_date]) if params[:end_date].present?
    @pets = @pets.where("city ILIKE ?", params[:city]) if params[:city].present?
    respond_to do |format|
      format.html
      format.text { render partial: "pets/pet_info", locals: { pets: @pets }, formats: [:html] }
    end
  end

  def show
    @coords = {
      lat: @pet.latitude,
      lng: @pet.longitude
    }
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to @pet, notice: "Successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_url, notice: "Successfully destroyed."
  end


  private

  def pet_params
    params.require(:pet).permit(:name, :age, :address, :postcode, :description, :price, :start_date, :end_date, :category, :photo, :country, :city)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_profile_completion, :set_profile, only: %i[edit update destroy remove_image]

  def show
    @profile = Profile.find_by(id: params[:id])
    return redirect_to root_path, flash: { error: "Profile not found" } unless @profile
  end

  def new
    if current_user.profile.present?
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = current_user.build_profile
    end
  end

  def edit
  end

  def create
    check_selected_roles(profile_params[:role])
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to @profile, notice: "Profile successfully created!"
    else
      render :new
    end
  end

  def update
    if profile_params[:role].present?
      profile_params[:role] = [profile_params[:role]] # Convert the value to an array
    else
      profile_params.delete(:role) # Remove the parameter if it's empty
    end

    if @profile.update(profile_params)
      redirect_to root_path, notice: "Profile successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    if @profile.destroy
      flash[:notice] = "Profile successfully deleted."
      redirect_to new_profile_path, notice: "Please create a new profile."
    else
      flash[:error] = "Failed to delete profile."
      redirect_back(fallback_location: root_path)
    end
  end

  def remove_image
    @profile.photo.purge if @profile.photo.attached?
    redirect_to edit_profile_path(@profile), notice: "Image successfully removed."
  end

  def dashboard
    @user = current_user
    @requests_received = @user.pet_requests
    @profile = current_user.profile
  end

  private

  def check_selected_roles(roles)
    if roles.present?
      # Print out or log the selected roles
      Rails.logger.info "Selected roles: #{roles}"
    else
      # Handle the case where no roles are selected
      Rails.logger.info "No roles selected"
    end
  end

  def set_profile
    @profile = current_user.profile
  end

  def check_profile_completion
    return if current_user.profile.present?

    flash[:error] = "Please create a profile before continuing."
    redirect_to new_profile_path
  end

  def profile_params
    puts "Role Param: #{params[:role]}"
    params.require(:profile).permit(:first_name, :last_name, :phone_number, :description, :age, :photo, :role)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:accept, :decline]

  def create
    @pet = Pet.find(params[:pet_id])
    @request = Request.new(user_id: current_user.id, pet_id: @pet.id)

    if @request.save
      redirect_to @pet, notice: "Request sent!"
    else
      flash[:error] = "Failed to send request."
      redirect_to @pet
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @pet = Pet.find(params[:pet_id])
    @owner = @pet.user
    @review = Review.new(review_params)
    @review.user = @owner
    if @review.save
      redirect_to pet_path(@pet), notice: 'Review was successfully created.'
    else
      redirect_to pet_path(@pet), alert: 'Failed to create review.'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPetSitterProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('Pet-sitter-banner.jpg') %>);">
  <div class="container">
    <h1>Find your next furry friend to take care of</h1>
    <p class="mb-3">Connect with pet owners in your area who need trusted pet sitters</p>
    <%= link_to "Search now", pets_path, class: 'btn btn-info btn-lrg mt-3' %>
  </div>
</div>

<div class="container">
  <h3 class="mt-3">Meet some recent additions</h3>

  <div class="row mt-3">
    <% if @pets %>
      <% @pets.each do |pet| %>
        <div class="col-4 mb-4">
          <%= link_to pet_path(pet.id), class:"flat-card-link" do %>
            <div class="card pet-card">
              <img class="card-img-top" src="<%= cl_image_path pet.photo.key %>" style="object-fit: cover; width: 100%; height: 300px;">
              <div class="card-body bg-light d-flex flex-column">
                <div>
                  <div class="card-title">
                    <h3><strong><%= pet.name.capitalize %></strong></h3>
                  </div>
                  <p><%= pet.description.capitalize %></p>
                </div>
                <div class="mt-auto d-flex justify-content-between">
                  <div>
                    <i class="fa-solid fa-house"></i>
                    <span><%= pet.city %></span>
                  </div>
                  <div>
                    <i class="fa-solid fa-sterling-sign"></i>
                    <% if pet.price % 1 != 0 %>
                      <span><%= sprintf('%.2f', pet.price) %> / day</span>
                    <% else %>
                      <span><%= pet.price.round %> / day</span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pets/pet_listings.html.erb
<% if current_user.pets.present? %>
  <div class="container">
    <div class="container d-none" data-controller="filter-pets"></div>

    <h3 class="mt-3">You Have <%= current_user.pets.size %> Pets</h3>
    <div class="requests-btn mt-3">
      <%= link_to "View Pet Sitting Requests", "/dashboard", class: "btn btn-info btn-lg" %>
    </div>

    <div class="row mt-4">
      <% current_user.pets.each do |pet| %>
        <div class="col-4 mb-4">
          <%= link_to pet_path(pet.id), class:"flat-card-link" do %>
            <div class="card pet-card">
              <img class="card-img-top" src="<%= cl_image_path pet.photo.key %>" style="object-fit: cover; width: 100%; height: 300px;">
              <div class="card-body bg-light d-flex flex-column">
                <div>
                  <div class="card-title">
                    <h3><strong><%= pet.name.capitalize %></strong></h3>
                  </div>
                  <p><%= pet.description.capitalize %></p>
                </div>
                <div class="mt-auto d-flex justify-content-between">
                  <div>
                    <i class="fa-solid fa-house"></i>
                    <span><%= pet.city %></span>
                  </div>
                  <div>
                    <i class="fa-solid fa-sterling-sign"></i>
                    <% if pet.price % 1 != 0 %>
                      <span><%= sprintf('%.2f', pet.price) %> / day</span>
                    <% else %>
                      <span><%= pet.price.round %> / day</span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
<% else %>
  <div class="container">
    <div class="container d-none" data-controller="filter-pets">
    </div>
    <h1 class="mt-3">Your pets:</h1>
    <p><strong>You dont have any pets!</strong></p>
    <%= link_to "Add pet", new_pet_path, class: "btn btn-info" %>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
<% end %>

app/views/pets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <!-- PET IMAGE AND INFO CONTAINER -->
      <div class="card bg-light mt-3">
            <div class="col-md-12 text-center petcontainer">
                <!-- PET IMG -->
                <%= cl_image_tag @pet.photo.key, class: "pet-image", alt: @pet.name, gravity: :center, crop: :fill %>
            </div>
            <!-- PET INFO -->
            <div class="infopet"> <!-- Center the text -->
                <!-- IMAGES CATEGORY -->
                <% image_url = case @pet.category
                when 'Dog'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883789/5fb72f5daf6bc223a1acb628aeaaf023_ayw7l8.svg'
                when 'Cat'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883801/9e731b68e6be3e403f5a9da3d42ceb4a_cljpqm.svg'
                when 'Rabbit'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883841/265291b777d57c71c4ab5a80b819b14f_lj5plw.svg'
                when 'Ferret'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883847/5c66582570be738a966e3bbfb7891eca_vvnqbk.svg'
                when 'Fish'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883873/8a750e6469cf33f18d5a46a7252f415d_gpbw0e.svg'
                when 'Bird'
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883898/01c52ec83a4efaf586efc278cf00b258_exetbe.svg'
                else
                  'https://res.cloudinary.com/dg9mc7ach/image/upload/v1708883940/f921728c3016d82b09e9d7b9e4145c09_q06owg.svg'
                end %>
              <!-- Image Category -->
              <div class="pet-image-category"><%= cl_image_tag image_url, alt: @pet.name %></div>
              <div class="harthlogo">
                <%= cl_image_tag "https://res.cloudinary.com/dg9mc7ach/image/upload/v1708950159/red-heart-icon_suoupl.svg", alt: "Harth Image" %>
              </div>
              <!-- PET NAME -->
              <strong id="petname"><%= @pet.name.capitalize %></strong>
              <% if @pet.country.present? %>
                <span class="flag-icon flag-icon-<%= @pet.country.downcase %>"></span>
              <% end %>
              <p id="petage"><%= @pet.age %> years old</p>
              <div class="pet-details">
                <!-- TABS -->
                <div class="pet-info" data-controller="show-pets">
                <!-- Tab Buttons -->
                <div class="tab-buttons">
                  <button data-action="click->show-pets#showTab" data-tab-target="0">About Pet</button>
                  <button data-action="click->show-pets#showTab" data-tab-target="1">Owner</button>
                  <button data-action="click->show-pets#showTab" data-tab-target="2">Care Details</button>
                  <button data-action="click->show-pets#showTab" data-tab-target="3">Reviews</button>
                </div>

                <!-- Tab Contents -->
                <div class="tab-content" data-show-pets-target="tabContent" data-tab-target="0">
                  <!-- About Tab Content -->
                  <p id="pet-description"><%= @pet.description %></p>
                </div>
                <div class="tab-content" data-show-pets-target="tabContent" data-tab-target="1">
                  <!-- Owner Tab Content -->
                  <div class="owner-photo">
                    <% if @pet.user.profile.photo.attached? %>
                      <%= cl_image_tag @pet.user.profile.photo.key, class: "rounded-circle", width: 250, height: 250, crop: :thumb, gravity: :center, alt: "Profile Picture" %>
                      <% else %>
                        <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "rounded-circle", width: 150, height: 150, alt: "Default Profile Picture" %>
                      <% end %>
                    <div class="owner-info">
                      <h2><%= @pet.user.profile.first_name %> <%= @pet.user.profile.last_name %></h2>
                      <p><%= @pet.user.profile.description %></p>
                    </div>
                  </div>
                </div>
                <div class="tab-content" data-show-pets-target="tabContent" data-tab-target="2">
                  <!-- Care Details Tab Content -->
                  <p id="owner-care">🐾 Celebrating My Beloved <strong><%= @pet.name.capitalize %></strong> 🐾
                  <ul>
                    <li>Feeding time = happy time!</li>
                    <li>Exploring and playing with my lovely companion.</li>
                    <li>Keeping <%= @pet.name.capitalize %> looking sharp and feeling fresh.</li>
                    <li>Regular vet check-ups to keep my buddy healthy.</li>
                    <li>Teaching tricks and learning together.</li>
                    <li>Making our home a safe haven for <%= @pet.name.capitalize %>.</li>
                    <li>Showering my furry friend with endless affection!</li>
                  </ul>
                  <p>Here's to many more joyful moments with <%= @pet.name.capitalize %>! ❤️🐾 <a href="#">#PetLove</a> <a href ="#">#BestCompanion</a>
                  <a href ="#">#PetParentLife</a>
                  <a href ="#">#PetLOVERS</a>
                  </p>
                </div>
                <div class="tab-content" data-show-pets-target="tabContent" data-tab-target="3">
                  <!-- Reviews Tab Content -->
                  <h2>John Doe</h2>
                  <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "rounded-circle", width: 45, height: 45, alt: "Default Profile Picture" %>
                  <br>
                  <p>⭐️⭐️⭐️⭐️⭐️</p>
                  <p>
                    "I had the pleasure of looking after <%= @pet.name.capitalize %> for a week and it was an amazing experience. <%= @pet.name.capitalize %> is a very well-behaved and loving pet. I would definitely look after <%= @pet.name.capitalize %> again in the future."
                  </p>
                  <h2>Jane Doe</h2>
                  <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "rounded-circle", width: 45, height: 45, alt: "Default Profile Picture" %>
                  <br>
                  <p>⭐️⭐️⭐️⭐️⭐️</p>
                  <p>
                    "I had the pleasure of looking after <%= @pet.name.capitalize %> very lovely and friendly pet. I already miss <%= @pet.name.capitalize %>"
                  </p>
                </div>
              </div>
            </div>
          </div>
          <!-- END PET IMAGE AND INFO CONTAINER -->
      </div>
    </div>
    <div class="col-md-6 p-3">
      <!-- PET PRICE AND DATES -->

      <div class="card p-3 bg-light">
        <p id="table-price">From <i class="fas fa-lira-sign" style="color: green;"><%= @pet.price.to_i %></i> per day</p>
        <div class="tabledate">
          <div class="tabledate-item">
            <strong><p>Sitter required</p></strong>
            <%= @pet.start_date.strftime("%d %b") %> - <%= @pet.end_date.strftime("%d %b") %>
          </div>
          <div class="tabledate-item">
            <strong><p>Care duration</p></strong>
            <% start_date = @pet.start_date %>
            <% end_date = @pet.end_date %>
            <% duration = (end_date - start_date).to_i %>
            <p><%= duration %> days</p>
          </div>
          <div class="tabledate-item">
            <strong><p>Location</p></strong>
            <p><%= @pet.city %> <%= @pet.country %></p>
          </div>
        </div>

        <!-- CURRENT USER LOOK AFTER -->
        <% if current_user.id == @pet.user_id %>
          <div class="d-inline-flex mt-3">
            <%= link_to "Edit", edit_pet_path(@pet.id), class: "btn btn-primary btn-edit ms-2" %>
            <%= link_to "Delete", pet_path(@pet.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-delete ms-2" %>
          </div>
        <% else %>
          <%= link_to "Apply for care #{@pet.name.capitalize}",
                      pet_requests_path(@pet.id),
                      data: { turbo_method: :post, turbo_confirm: "Are you sure?" },
                      class: 'btn btn-info btn-care mt-3' %>
        <% end %>
        <!-- END CURRENT USER LOOK AFTER -->
      </div>

      <!-- GEOLOCATION -->
      <div class="card bg-light mt-3 p-3">
        <div id="map" style="width: 100%; height: 400px;"
          data-controller="map"
          data-map-coords-value="<%= @coords.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-6 mt-3">
    <div class="card shadow">
      <div class="card-body">
        <h1 class="card-title text-center">Edit Your Profile</h1>
        <div class="mt-3">
          <%= simple_form_for @profile, url: profile_path(@profile), method: :patch do |form| %>
            <!-- Display the current profile picture -->
            <% if @profile.photo.attached? %>
              <div class="text-center mb-3">
                <%= cl_image_tag @profile.photo.key, class: "photo-profile-img", width: 250, height: 250, crop: :thumb %>
              </div>
              <div class="text-center">
                <%= link_to remove_profile_image_path(@profile), data: { turbo_method: :delete, confirm: "Are you sure you want to delete the picture?"}, class: "btn btn-danger", "turbo-frame": "profile-form-frame" do %> <!-- Allow the user to remove the profile picture -->
                  <i class="fas fa-trash-alt"></i> Delete Photo
                <% end %>
              </div>
            <% else %>
              <div class="text-center mb-3">
                <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar", alt: "default picture" %> <!-- Display a default profile picture if the user doesn't have one -->
              </div>
              <div class="text-center">
                <%= form.input :photo, as: :file, label: 'Profile image', class: 'form-control-file' %> <!-- Allow the user to upload a profile picture -->
              </div>
            <% end %>
            <div class="form-group">
              <%= form.input :first_name, label: "First Name", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.input :last_name, label: "Last Name", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.input :description, label: "Description", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.input :age, label: "Age", class: "form-control" %>
            </div>
            <div class="text-center">
              <%= form.button :submit, "Save Changes", class: "btn btn-primary" %>
              <%= link_to "Delete Profile", profile_path(@profile), data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-6 m-auto mt-3">
    <div class="bg-light p-3">
      <h1>Create your profile</h1>
      <div class="mt-3">
        <%= simple_form_for @profile || current_user.build_profile, url: profiles_path, method: :post do |form| %>
          <%= form.input :photo %>
          <%= form.input :first_name %>
          <%= form.input :last_name %>
          <%= form.input :description %>
          <%= form.input :phone_number %>
          <%= form.input :age %>
          <br>
          <br>
          <%= form.button :submit, class: "btn btn-info"%>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "Best-pet-sitter-logo.png", alt: "Best Pet Sitter logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Pet Sit", pets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Pet", new_pet_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown ms-1">
          <!-- PROFILE & LOGIC -->
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.profile.present? && current_user.profile.photo.attached? %>
                <%= cl_image_tag current_user.profile.photo.key, class: "avatar-img rounded-circle border", alt: "dropdown menu", width: 45, height: 45, crop: :thumb, gravity: :face %>
              <% else %>
                <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.profile.present? && current_user.profile.id.present? %>
                <%= link_to user_profile_path(current_user.profile), class: "dropdown-item" do %>
                  <i class="fas fa-cogs"></i> Configure Profile
              <% end %>

              <!-- IF USER HAS PETS, SHOW LINK TO THEM -->
              <% if current_user.pets.present? %>
                <%= link_to "My Pets", pet_listings_pets_path, class: "dropdown-item" %>
              <% end %>

              <% if current_user.requests.present? %>
              <!-- INSERT LINK TO REQUESTS PAGE BELOW -->
                  <%= link_to "My Pet Sittings", "", class: "dropdown-item" %>
              <% end %>

              <% else %>
                <!-- Alert message for users without a profile -->
                <div class="alert alert-warning" role="alert">
                  You haven't created a profile yet. Please create your profile to continue.
                </div>
                <!-- Link to create profile for users without a profile -->
                <%= link_to "Create Profile", new_profile_path, class: "dropdown-item" %>
              <% end %>
          <!-- ENDING PROFILE & LOGIC -->
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>